{% set name = "interpret" %}
{% set version = "0.6.8" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/852e697f9f77f977a57894b32da604d227ed632e.tar.gz
  sha256: 5cce02eff550448e1a361fa243f549943e3d7b10a92927858afa947fa37a64c3

build:
  number: 0
  noarch: python
  script: cd ./python/interpret/ && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - interpret-core =={{ version }}
    # Equiv. to extras.
    - psutil >=5.6.2
    - ipykernel >=4.10.0
    - ipython >=5.5.0
    - plotly >=3.8.1
    # - lime >=0.1.1.33  # no longer maintained
    - SALib >=1.3.3
    - shap >=0.28.5
    - dill >=0.2.5
    # - skope-rules >=1.0.1    fails on python 3.10
    # - treeinterpreter >=0.2.2  # no longer maintained
    - dash >=1.0.0 # dash 2.* removed the dependencies on: dash-html-components, dash-core-components, dash-table
    - dash-core-components >=1.0.0 # dash 2.* removes the need for this dependency
    - dash-html-components >=1.0.0 # dash 2.* removes the need for this dependency
    - dash-table >=4.1.0 # dash 2.* removes the need for this dependency
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0

test:
  requires:
    - python {{ python_min }}
    # for pip check
    - pip
    # pure test requirements
    - scipy >=0.18.1
    - pytest >=4.3.0
    - pytest-runner >=4.4
    - pytest-xdist >=1.29
    - nbconvert >=5.4.1
    - selenium >=3.141.0
    - pytest-cov >=2.6.1
    - flake8 >=3.7.7
    - jupyter >=1.0.0
    - ipywidgets >=7.4.2
  source_files:
    - python/interpret-core/tests/**
  imports:
    - interpret
  commands:
    # - pip check
    # - pip list
    - python -m pytest -vv -n auto --junitxml=junit/test-results.xml --cov=interpret --cov-report=xml --cov-report=html python/interpret-core/tests --ignore=python/interpret-core/tests/glassbox/test_aplr.py

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable models. Explain blackbox machine learning.
  description: |
    In the beginning machines learned in darkness, and data scientists struggled in the void to explain them.

    Let there be light.

    https://github.com/interpretml/interpret
  license: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
